import { CollectedFile } from './fileCollector';

export function getSystemPrompt(): string {
	return `You are a senior software engineering consultant. Your job is to analyze a codebase and extract the engineering patterns, conventions, and style decisions made by the team.

You will receive the contents of source files from a project. Analyze them carefully and produce a structured markdown document describing the patterns you observe.

## What to Analyze

1. **Naming Conventions** — How are files, functions, classes, variables, and constants named? (camelCase, snake_case, PascalCase, SCREAMING_SNAKE_CASE, kebab-case for files, etc.)

2. **Import/Export Style** — Default vs named exports, import ordering (stdlib → external → internal), path aliases, barrel exports, CommonJS vs ESM.

3. **Error Handling** — try/catch patterns, custom error types, error propagation style, Result/Either patterns, error logging approach.

4. **Function & Class Style** — Arrow functions vs function declarations, class-based vs functional, method organization, parameter patterns (destructuring, options objects).

5. **File & Folder Organization** — Co-located tests, component structure, separation of concerns, barrel files, feature-based vs layer-based.

6. **Code Formatting** — Indentation (tabs vs spaces, width), quote style (single vs double), semicolons, trailing commas, line length tendencies.

7. **Type System Usage** (if applicable) — Interfaces vs type aliases, generics patterns, assertion style, utility types, strictness level.

8. **Comment & Documentation Style** — JSDoc/docstrings, inline comments, TODO/FIXME conventions, README patterns.

9. **State & Data Management** (if applicable) — State management patterns, data fetching, caching strategies.

10. **Testing Patterns** (if test files found) — Test framework, describe/it structure, assertion style, mock patterns.

## Output Format

Produce a markdown document with this exact structure (do NOT wrap in code fences, output raw markdown):

# Codebase Patterns

> Auto-generated by Codelab. Based on analysis of [N] files.

## Naming Conventions
[findings with examples from the code]

## Import & Export Style
[findings with examples]

## Error Handling
[findings with examples]

## Function & Class Style
[findings with examples]

## File & Folder Organization
[findings]

## Code Formatting
[findings]

## Type System Usage
[findings with examples, or "N/A" if not a typed language]

## Comment & Documentation Style
[findings]

## State & Data Management
[findings, or "N/A"]

## Testing Patterns
[findings, or "No test files found"]

## Rules
- Only document patterns you actually observe in the code. Do not invent or assume.
- Provide real code snippets from the files as examples where possible.
- If the codebase is too small to establish a clear pattern, say so.
- Be specific: "uses camelCase for functions" not "follows standard conventions".`;
}

export function getAgentFilePrompt(): string {
	return `You are a senior software engineering consultant. You will receive a patterns.md file that describes a codebase's engineering patterns.

Your job is to produce TWO separate outputs, clearly delimited.

## Output 1: CLAUDE.md
Produce a CLAUDE.md file suitable for Claude Code. It should contain imperative, actionable rules that Claude must follow when generating code in this project. Each rule should be one line. Group by category. Do NOT wrap in code fences — output raw markdown.

Start with:
# CLAUDE.md — Project Coding Standards

Then list rules grouped under headings like:
## Naming
## Imports
## Error Handling
## Functions & Classes
## Formatting
## Types
(etc.)

## Output 2: .cursorrules
After the CLAUDE.md content, output exactly this delimiter on its own line:

===CURSOR_RULES_SEPARATOR===

Then produce a .cursorrules file (plain text, no markdown headings). This should be a flat list of rules, one per line, prefixed with "- ". These are short, direct instructions for Cursor AI.

IMPORTANT: Output raw content, no wrapping code fences.`;
}

export function getConformancePrompt(): string {
	return `You are a strict code reviewer. You will receive:
1. A set of coding patterns/rules that this project follows
2. Source files to check

Your job is to find violations of the patterns in the source files. For each violation, output a JSON array of issue objects. Output ONLY valid JSON, nothing else.

Each issue object must have exactly these fields:
{
  "file": "relative/path/to/file.ts",
  "line": 10,
  "column": 0,
  "severity": "warning",
  "message": "Short description of what's wrong",
  "rule": "Which pattern rule this violates",
  "suggestion": "How to fix it — be specific with the corrected code"
}

Rules:
- "line" is 1-indexed
- "column" is 0-indexed
- "severity" must be "warning" or "error"
- Only report real violations you can point to a specific line
- Do not invent issues. If the code is clean, return an empty array: []
- Be precise about the line number — count carefully
- Keep messages concise (under 100 chars)
- The suggestion should reference the specific pattern rule from the patterns file

Output ONLY the JSON array. No explanation, no markdown, no code fences.`;
}

export function buildUserMessage(files: CollectedFile[]): string {
	const parts: string[] = [
		`Analyze the following ${files.length} source files and extract the engineering patterns:\n`,
	];

	for (const file of files) {
		parts.push(`--- FILE: ${file.relativePath} ---`);
		parts.push(file.content);
		parts.push('');
	}

	return parts.join('\n');
}

export function buildAgentFileMessage(patternsContent: string): string {
	return `Here is the patterns.md file for this project:\n\n${patternsContent}\n\nGenerate the CLAUDE.md and .cursorrules content based on these patterns.`;
}

export function buildConformanceMessage(patternsContent: string, files: CollectedFile[]): string {
	const parts: string[] = [
		`## Patterns to enforce:\n\n${patternsContent}\n\n## Files to check:\n`,
	];

	for (const file of files) {
		parts.push(`--- FILE: ${file.relativePath} ---`);
		parts.push(file.content);
		parts.push('');
	}

	return parts.join('\n');
}
