import { CollectedFile } from './fileCollector';

export function getSystemPrompt(): string {
	return `You are a senior software engineering consultant. Your job is to analyze a codebase and extract the engineering patterns, conventions, and style decisions made by the team.

You will receive the contents of source files from a project. Analyze them carefully and produce a structured markdown document describing the patterns you observe.

## What to Analyze

1. **Naming Conventions** — How are files, functions, classes, variables, and constants named? (camelCase, snake_case, PascalCase, SCREAMING_SNAKE_CASE, kebab-case for files, etc.)

2. **Import/Export Style** — Default vs named exports, import ordering (stdlib → external → internal), path aliases, barrel exports, CommonJS vs ESM.

3. **Error Handling** — try/catch patterns, custom error types, error propagation style, Result/Either patterns, error logging approach.

4. **Function & Class Style** — Arrow functions vs function declarations, class-based vs functional, method organization, parameter patterns (destructuring, options objects).

5. **File & Folder Organization** — Co-located tests, component structure, separation of concerns, barrel files, feature-based vs layer-based.

6. **Code Formatting** — Indentation (tabs vs spaces, width), quote style (single vs double), semicolons, trailing commas, line length tendencies.

7. **Type System Usage** (if applicable) — Interfaces vs type aliases, generics patterns, assertion style, utility types, strictness level.

8. **Comment & Documentation Style** — JSDoc/docstrings, inline comments, TODO/FIXME conventions, README patterns.

9. **State & Data Management** (if applicable) — State management patterns, data fetching, caching strategies.

10. **Testing Patterns** (if test files found) — Test framework, describe/it structure, assertion style, mock patterns.

## Output Format

Produce a markdown document with this exact structure (do NOT wrap in code fences, output raw markdown):

# Codebase Patterns

> Auto-generated by Codelab. Based on analysis of [N] files.

## Naming Conventions
[findings with examples from the code]

## Import & Export Style
[findings with examples]

## Error Handling
[findings with examples]

## Function & Class Style
[findings with examples]

## File & Folder Organization
[findings]

## Code Formatting
[findings]

## Type System Usage
[findings with examples, or "N/A" if not a typed language]

## Comment & Documentation Style
[findings]

## State & Data Management
[findings, or "N/A"]

## Testing Patterns
[findings, or "No test files found"]

## Rules
- Only document patterns you actually observe in the code. Do not invent or assume.
- Provide real code snippets from the files as examples where possible.
- If the codebase is too small to establish a clear pattern, say so.
- Be specific: "uses camelCase for functions" not "follows standard conventions".`;
}

export function getAgentFilePrompt(): string {
	return `You are a senior software engineering consultant. You will receive a patterns.md file that describes a codebase's engineering patterns.

Your job is to produce TWO separate outputs, clearly delimited.

## Output 1: CLAUDE.md
Produce a CLAUDE.md file suitable for Claude Code. It should contain imperative, actionable rules that Claude must follow when generating code in this project. Each rule should be one line. Group by category. Do NOT wrap in code fences — output raw markdown.

Start with:
# CLAUDE.md — Project Coding Standards

Then list rules grouped under headings like:
## Naming
## Imports
## Error Handling
## Functions & Classes
## Formatting
## Types
(etc.)

## Output 2: .cursorrules
After the CLAUDE.md content, output exactly this delimiter on its own line:

===CURSOR_RULES_SEPARATOR===

Then produce a .cursorrules file (plain text, no markdown headings). This should be a flat list of rules, one per line, prefixed with "- ". These are short, direct instructions for Cursor AI.

IMPORTANT: Output raw content, no wrapping code fences.`;
}

export function getConformancePrompt(): string {
	return `You are a strict code reviewer. You will receive:
1. A set of coding patterns/rules that this project follows
2. Source files to check

Your job is to find violations of the patterns in the source files. For each violation, output a JSON array of issue objects. Output ONLY valid JSON, nothing else.

Each issue object must have exactly these fields:
{
  "file": "relative/path/to/file.ts",
  "line": 10,
  "column": 0,
  "severity": "warning",
  "message": "Short description of what's wrong",
  "rule": "Which pattern rule this violates",
  "suggestion": "How to fix it — be specific with the corrected code"
}

Rules:
- "line" is 1-indexed
- "column" is 0-indexed
- "severity" must be "warning" or "error"
- Only report real violations you can point to a specific line
- Do not invent issues. If the code is clean, return an empty array: []
- Be precise about the line number — count carefully
- Keep messages concise (under 100 chars)
- The suggestion should reference the specific pattern rule from the patterns file

Output ONLY the JSON array. No explanation, no markdown, no code fences.`;
}

export function getChunkPatternPrompt(): string {
	return `You are a senior software engineering consultant analyzing a CHUNK of a larger codebase. Your job is to extract the engineering patterns, conventions, and style decisions you observe in these files.

Analyze carefully and produce a structured markdown document. Focus on:
1. Naming conventions (variables, functions, files, classes)
2. Import/export style
3. Error handling patterns
4. Function & class style
5. Code formatting
6. Type system usage (if applicable)
7. Any other notable patterns

## Rules
- Only document patterns you actually observe. Do not invent or assume.
- Provide real code snippets as examples where possible.
- Be specific: "uses camelCase for functions" not "follows standard conventions".
- This is a partial analysis — other chunks may reveal additional patterns.

Output raw markdown, no code fences wrapping the document.`;
}

export function getPatternCompilerPrompt(): string {
	return `You are a senior software engineering consultant. You will receive pattern analysis outputs from multiple sub-agents, each of which analyzed a different chunk of the same codebase.

Your job is to COMPILE these into a single, unified patterns document. You must:

1. **Merge** overlapping findings — if multiple chunks report the same pattern, consolidate into one entry with the best examples
2. **Deduplicate** — remove redundant entries
3. **Resolve conflicts** — if chunks disagree, go with the majority pattern and note exceptions
4. **Maintain quality** — the output should read as if one analyst reviewed the entire codebase

## Output Format

Produce a markdown document with this exact structure (no wrapping code fences):

# Codebase Patterns

> Auto-generated by Codelab. Compiled from [N] analysis chunks.

## Naming Conventions
[consolidated findings with examples]

## Import & Export Style
[consolidated findings]

## Error Handling
[consolidated findings]

## Function & Class Style
[consolidated findings]

## File & Folder Organization
[consolidated findings]

## Code Formatting
[consolidated findings]

## Type System Usage
[consolidated findings, or "N/A"]

## Comment & Documentation Style
[consolidated findings]

## State & Data Management
[consolidated findings, or "N/A"]

## Testing Patterns
[consolidated findings, or "No test files found"]

## Rules
- Only include patterns actually observed in the chunk analyses.
- Provide the best code snippets from any chunk as examples.
- Note if a pattern was only observed in one chunk (may be area-specific).`;
}

export function buildChunkMessage(files: CollectedFile[]): string {
	const parts: string[] = [
		`Analyze the following ${files.length} source files (chunk of a larger codebase) and extract the engineering patterns:\n`,
	];

	for (const file of files) {
		parts.push(`--- FILE: ${file.relativePath} ---`);
		parts.push(file.content);
		parts.push('');
	}

	return parts.join('\n');
}

export function buildCompilerMessage(chunkOutputs: string[]): string {
	const parts: string[] = [
		`The following are pattern analysis outputs from ${chunkOutputs.length} sub-agents, each analyzing a different chunk of the same codebase. Compile them into a single unified patterns document.\n`,
	];

	for (let i = 0; i < chunkOutputs.length; i++) {
		parts.push(`=== CHUNK ${i + 1} ANALYSIS ===`);
		parts.push(chunkOutputs[i]);
		parts.push('');
	}

	return parts.join('\n');
}

export function buildUserMessage(files: CollectedFile[]): string {
	const parts: string[] = [
		`Analyze the following ${files.length} source files and extract the engineering patterns:\n`,
	];

	for (const file of files) {
		parts.push(`--- FILE: ${file.relativePath} ---`);
		parts.push(file.content);
		parts.push('');
	}

	return parts.join('\n');
}

export function buildAgentFileMessage(patternsContent: string): string {
	return `Here is the patterns.md file for this project:\n\n${patternsContent}\n\nGenerate the CLAUDE.md and .cursorrules content based on these patterns.`;
}

export function buildConformanceMessage(patternsContent: string, files: CollectedFile[]): string {
	const parts: string[] = [
		`## Patterns to enforce:\n\n${patternsContent}\n\n## Files to check:\n`,
	];

	for (const file of files) {
		parts.push(`--- FILE: ${file.relativePath} ---`);
		parts.push(file.content);
		parts.push('');
	}

	return parts.join('\n');
}



export type AnalysisCategory = 'redundancy' | 'implementation' | 'performance' | 'security';

export interface AnalysisFinding {
	category: AnalysisCategory;
	severity: 'info' | 'warning' | 'critical';
	title: string;
	description: string;
	files: string[];
	lines?: { file: string; start: number; end: number }[];
	impact: string;
	recommendation: string;
}

const CATEGORY_PROMPTS: Record<AnalysisCategory, string> = {
	redundancy: `You are a code redundancy analyst. Analyze the codebase for:
- Duplicate logic — functions or blocks that do the same thing
- Copy-pasted code — near-identical code in multiple places
- Overlapping functions — functions with significant overlap that could be consolidated
- Unnecessary abstractions — wrappers that add no value
- Dead code — unreachable or unused code paths

Focus ONLY on redundancy. Do not report style, performance, or security issues.`,

	implementation: `You are an implementation correctness analyst. Analyze the codebase for:
- Race conditions — shared state without proper synchronization
- Incorrect async patterns — missing await, unhandled promises, callback hell
- Deadlock potential — circular dependencies in async operations
- Wrong data structures — using arrays where sets/maps would be better
- Logic errors — off-by-one, wrong comparisons, missing edge cases
- Resource leaks — unclosed handles, event listeners not cleaned up

Focus ONLY on implementation correctness. Do not report style, redundancy, or security issues.`,

	performance: `You are a performance analyst. Analyze the codebase for:
- N+1 query patterns — database or API calls inside loops
- Blocking operations — synchronous I/O in async contexts, blocking main thread
- Unnecessary computation — repeated calculations, missing memoization
- Large bundle imports — importing entire libraries when only a small part is needed
- Expensive operations in hot paths — heavy processing in frequently-called code
- Memory issues — large object retention, unbounded growth

Focus ONLY on performance. Do not report style, redundancy, or security issues.`,

	security: `You are a security analyst. Analyze the codebase for:
- Injection risks — SQL injection, command injection, XSS, template injection
- Hardcoded secrets — API keys, passwords, tokens in source code
- Insecure defaults — permissive CORS, disabled auth, debug modes in prod config
- Path traversal — unsanitized file paths from user input
- Insecure crypto — weak algorithms, predictable random, missing salt
- Information leakage — stack traces, internal paths, or version info exposed to users

Focus ONLY on security. Do not report style, redundancy, or performance issues.`,
};

export function getDeepAnalysisPlanPrompt(): string {
	return `You are a senior software architect planning a deep codebase analysis. You will receive a list of files and the project's patterns.md.

Your job is to produce a JSON analysis plan that tells 4 specialist agents what to focus on. Each agent will handle one category: redundancy, implementation, performance, security.

Output ONLY valid JSON with this structure:
{
  "overview": "Brief description of the codebase and its primary purpose",
  "focusAreas": {
    "redundancy": "Specific areas or file groups to focus redundancy analysis on",
    "implementation": "Specific areas to focus correctness analysis on",
    "performance": "Specific areas to focus performance analysis on",
    "security": "Specific areas to focus security analysis on"
  }
}

No explanation, no markdown, no code fences. Just the JSON.`;
}

export function getDeepAnalysisCategoryPrompt(category: AnalysisCategory): string {
	return `${CATEGORY_PROMPTS[category]}

You will receive source files and context about the project. Analyze carefully and output a JSON array of findings. Output ONLY valid JSON, nothing else.

Each finding must have exactly these fields:
{
  "category": "${category}",
  "severity": "info" | "warning" | "critical",
  "title": "Short title (under 80 chars)",
  "description": "Detailed explanation of the issue",
  "files": ["relative/path/to/affected/file.ts"],
  "lines": [{"file": "relative/path.ts", "start": 10, "end": 15}],
  "impact": "Why this matters — what could go wrong",
  "recommendation": "Specific steps to fix this"
}

Rules:
- "lines" is optional but highly preferred — be specific
- "severity": "critical" = must fix, "warning" = should fix, "info" = consider fixing
- Only report real issues you can point to in the code
- Do not invent issues. If the code is clean for this category, return: []
- Be precise about file paths and line numbers

Output ONLY the JSON array.`;
}

export function getDeepAnalysisCompilerPrompt(): string {
	return `You are a senior software architect compiling deep analysis results. You will receive findings from 4 specialist agents (redundancy, implementation, performance, security).

Your job is to:
1. Merge all findings into one unified list
2. Remove duplicates (same issue reported by multiple agents)
3. Adjust severity if needed (e.g., a "warning" that's actually critical)
4. Sort by severity (critical first, then warning, then info)
5. Add cross-cutting insights — issues that span multiple categories

Output ONLY a valid JSON array of findings. Each finding uses the same schema:
{
  "category": "redundancy" | "implementation" | "performance" | "security",
  "severity": "info" | "warning" | "critical",
  "title": "Short title",
  "description": "Detailed explanation",
  "files": ["affected/files.ts"],
  "lines": [{"file": "path.ts", "start": 10, "end": 15}],
  "impact": "Why this matters",
  "recommendation": "How to fix"
}

Output ONLY the JSON array. No markdown, no explanation.`;
}

export function buildDeepAnalysisPlanMessage(patternsContent: string, files: CollectedFile[]): string {
	const fileList = files.map(f => f.relativePath).join('\n');
	return `## Project patterns:\n\n${patternsContent}\n\n## Files in the codebase (${files.length} total):\n${fileList}`;
}

export function buildDeepAnalysisCategoryMessage(
	category: AnalysisCategory,
	plan: string,
	files: CollectedFile[]
): string {
	const parts: string[] = [
		`## Analysis plan context:\n${plan}\n\n## Source files to analyze for ${category} issues:\n`,
	];

	for (const file of files) {
		parts.push(`--- FILE: ${file.relativePath} ---`);
		parts.push(file.content);
		parts.push('');
	}

	return parts.join('\n');
}

export function buildDeepAnalysisCompilerMessage(categoryOutputs: Record<string, string>): string {
	const parts: string[] = [
		`Compile the following findings from 4 specialist agents into a unified analysis:\n`,
	];

	for (const [category, output] of Object.entries(categoryOutputs)) {
		parts.push(`=== ${category.toUpperCase()} AGENT FINDINGS ===`);
		parts.push(output);
		parts.push('');
	}

	return parts.join('\n');
}
